### ISSUE TITLE
Comportement étrange squelettes (Donjon 1)

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#15]
Dans le donjon 1, les squelettes ont de temps en temps (environ 1 fois sur 10) un comportement étrange : ils disparaissent après le premier mouvement (je pense même après l'animation où ils tournent la tête), mais les collisions restent : si on va sur l'emplacement où ils étaient on prend des dégâts et si on tape à l'endroit où ils ont disparu, ils réapparaissent (animation blessure), refont un mouvement et à la fin redisparaissent. Ils peuvent mourir normalement.

Pour le constater : faire des allers retours entre le sous-sol (où il y a la porte du boss) et la salle principale et observer les squelettes.

**Comment by Renkineko** [comment]
Apparently, fix bff0c12 seems OK. Closing the issue, I'll reopen if I encounter the bug again.

**Comment by Renkineko** [comment]
I confirm the bug still exists with Solarus 1.4.5 after reverting bff0c12, good news : it happened on my ubuntu session (totally different pc), so it's not specific to the os nor my hardware (the only common is the hard drive where the quest is, not even the engine is on the same drive than my first encounter with this problem ^^), you should be able to do it. Nothing to see in the console when happened.

**Comment by christopho** [comment]
Thanks to Renkineko we have more information: in LuaContext::userdata_has_field(), userdata.is_with_lua_table() is false. Maybe the function on_animation_finished() is assigned too late on the sprite, its animation finishes immediately?

**Comment by christopho** [comment]
More information again (thanks @Renkineko): if we make LuaContext::userdata_has_field() just return true, the bug still exists.
So, sprite:on_animation_finished() is really not found for some reason, it is not a wrong behavior of userdata_has_field().

**Comment by Renkineko** [comment]
It's not a quest related issue: if you copy and paste the skeleton sprite and script on another quest (for my test, I imported them in my nrfh repository), the same issue happens. Maybe we should close the issue here and open the issue on the engine?

**Comment by christopho** [comment]
This issue was moved to christopho/solarus#799
