### ISSUE TITLE
Plus de musique sur l'étage après avoir tué le boss (Donjon 1)

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#16]
Dans le donjon 1, lorsqu'on tue le boss, la musique de victoire se joue. Si on reste un peu dans l'étage, il n'y a plus de musique. En revenant au RDC, la musique se relance.

**Comment by Maxs1789** [comment]
Pareil au donjon 5, peut être tous les autres aussi.

**Comment by christopho** [comment]
Oui c'est normal.
