### ISSUE TITLE
Erreur en sauvegardant + quittant dans l'armurerie de Cocorico

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#18]
Erreur dans la console lorsque j'ai save + quit dans l'armurerie de Cocorico (où on a l'arc) : 

Error : In on_started: [string "maps/outside/c3.lua"]:9: bad argument #1 to start (table, entity or drawable expected, got nil)

Aucune incidence in game.

**Comment by christopho** [comment]
Already fixed
