### ISSUE TITLE
Gros lag des medusa

### ISSUE THREAD

**Issue by Maxs1789** [christopho/zelda_roth_se#19]
Lorsque je me retrouve dans une salle avec plusieurs medusa (donjon 6) j'ai d'énormes lags.

![capture-zelda return of the hylian-1](https://cloud.githubusercontent.com/assets/573681/9236225/cd052628-4143-11e5-9413-26fdeff5ee3a.png)

Les lags se produisent lorsque ceux-ci tirent des boules de feu.

**Comment by christopho** [comment]
Moi j'ai un gros lag en debug et ça se passe bien en release.

**Comment by Renkineko** [comment]
En fait, même sans les medusas : dans cette salle, je rame beaucoup en utilisant le grappin

![image](https://cloud.githubusercontent.com/assets/2254151/9258330/25033678-41fb-11e5-8e5b-e1702255d562.png)

Endroit du donjon : 
![image](https://cloud.githubusercontent.com/assets/2254151/9258332/2ec9e88c-41fb-11e5-8e8e-c1fe66bc8e65.png)

**Comment by Renkineko** [comment]
C'est beaucoup mieux pour ma part, mais j'ai quand même un peu de lag quand j'utilise le grappin dans la salle de droite avec les medusas (enfin, quand elles ont toutes fait feu quoi). C'est moins prononcé qu'avant, mais ça rame quand même.

**Comment by christopho** [comment]
Le moteur 1.5 améliorera la situation. Côté quête on se contentera de ce fix pour le moment.
