### ISSUE TITLE
Strange behaviour with Caps Lock

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#20]
When you use Caps Lock for the Auto-run, if you have stop the game (save & quit) but don't close the window of the game, change windows and remove caps lock (for chat or anything), and you come back to the game, you have to do the caps lock two times to reactivate the auto-run (like if the first one wasn't taken in account because the state is already known ?)

**Comment by Renkineko** [comment]
Happens also after a game over

**Comment by Renkineko** [comment]
If you just tap shift, the autorun is back without having to jungle with caps lock.

**Comment by christopho** [comment]
Note that on X11, with SDL < 2.0.4, starting solarus while caps lock on gives inverted behavior of caps lock. This is fixed in SDL 2.0.4: https://bugzilla.libsdl.org/show_bug.cgi?id=2736
