### ISSUE TITLE
Donjon 3: Boss bloqué

### ISSUE THREAD

**Issue by Maxs1789** [christopho/zelda_roth_se#3]
Lors du combat contre le boss du 3ème donjon, si on se laisse tomber dans le trou par le bas (à droite au gauche), on réapparaît à l'entrée de la salle; le boss peut alors se retrouver bloqué au dessus du vide.

![dungeon3_boss](https://cloud.githubusercontent.com/assets/573681/9212982/1e751fe2-408e-11e5-9e8a-57c994b00742.png)

Si on le tue la, le cristal tombe dans le trou. Mais il reste récupérable ensuite.

**Comment by christopho** [comment]
D'ailleurs Il y avait le même "bug" dans l'original, j'en profitais dans le speedrun :)
