### ISSUE TITLE
Erratic behaviour of the ctrl + direction 

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#34]
When you do ctrl + direction, you have the possibility to look around. If you are not straight on the direction (taping repeatly on the key), sometimes the hero will move and sometimes the expected behaviour (camera control) will take place.

**Comment by christopho** [comment]
The bug is mostly fixed. It still happens sometimes but much less frequently and the hero moves less when it happens.
For a really perfect fix, we would need the new camera API of Solarus 1.5.
