### ISSUE TITLE
Coeurs manquant

### ISSUE THREAD

**Issue by Maxs1789** [christopho/zelda_roth_se#37]
J'ai obtenu les 36 quarts de coeur, mais il me manque 2 coeurs complet et lorsque je termine le jeu, il m'indique que j'en ai 27 / 36.

Je précise tout de même que je jouais avec le mode debug et que certains dialogues de quart de coeur    était passé rapidement avec la touche `Shift` (du mode debug) qui sert dans ce jeu à courir.

**Comment by Maxs1789** [comment]
J'ai fais quelques tests, mais je ne parvient pas a reproduire le bug de manière simple (en récupérant directement 36 quarts de coeur, avec Shift ou sans, via la console ou in-game). À la fin, j'ai toujours le bon nombre de coeurs et les stats indique bien 36 / 36.

J'ai peut être fait quelque chose qu'il ne fallait pas, même si je pense n'avoir utilisé les cheats que pour tenter de régler mon problème avec l'arc (donc rien à voir).

Bref, il faudrait que quelqu'un d'autre ayant terminé le jeu à 100% nous dise si il a rencontré ou pas ce genre de soucis.

**Comment by christopho** [comment]
Renkineko dit qu'il n'a pas le problème non plus. J'ai sûrement ajouté le compteur de quarts de cœur total après que tu as commencé ta partie.
