### ISSUE TITLE
No secret sound when resolve a room dungeon 6

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#38]
In this room, you have to deflect balls sent by medusa to lit torches, but when you do it the "secret" sound is not played (or at least it has not been played for me this time ?), can you check ? 

![image](https://cloud.githubusercontent.com/assets/2254151/9243172/3a9b50d8-418d-11e5-9782-913e107b2605.png)

**Comment by christopho** [comment]
Cannot reproduce the bug. It is probably a problem with the engine because the game code is common for all rooms with torches like that.

**Comment by christopho** [comment]
Or maybe there was a Lua error that interrupted the function. If you reproduce the bug, can you look at errors? Thanks

**Comment by Renkineko** [comment]
I reproduced the bug on my 100% play with the official release, and I didn't saw a problem on the console (but maybe I just closed the game without looking at it). I'll try again this week-end with an ultimate test and I'll see if I see an error or not. But the two rooms have not the secret sound played, that's sure (this one and the one underneath or just above, can't remember :s )
