### ISSUE TITLE
Sometimes, Ice Ground is not slipping

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#41]
I use the autorun and if I tap on the arrow, the hero is not always slipping on the icy ground. Don't know when it works and when it doesn't.

**Comment by Renkineko** [comment]
Un autre bug (je l'explique en français car en anglais je vais trop galérer) : dans la première salle avec des zigzags au dessus du vide et tout en sol glissant, j'ai eu un bug qui m'empêchait d'avancer tout droit : aller vers l'avant (donc : en haut quand le héros regarde vers le haut, en bas quand il regarde en bas, à droite etc) me faisait reculer (le mouvement était inversé en somme). Si je restais appuyé assez longtemps, le mouvement reprenait, mais le recul (on va dire que la glissade) finissait inversée...

Très très étrange à visualiser. Pour le déclencher je pense juste que j'ai tapoté pas mal de direction en même temps pour m'ajuster.

**Comment by christopho** [comment]
Already fixed in 1.0.0 (engine bug)

**Comment by Renkineko** [comment]
OK, so I found about the second bug what is the trigger : when you are about to fall in a hole but you escape from it, then the hero movement are completely f**ked up. Right now, I can move only 1pixel at a time before going to quickly on a direction and slipping in the hole (when there is long straight line of ground ok, but turn are pain in the *ss ^^). I think the movement are ok again when quitting the icy ground

**Comment by Renkineko** [comment]
https://youtu.be/hV4r3l9Om50 a youtube video to show my movement after the bug occurs.
