### ISSUE TITLE
Ice wand doesn't work on water

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#42]
Once you got the Ice Wand, you should be able to make water walkable. When you use the wand, the tiles are created but you swim on them instead of walking : 

![image](https://cloud.githubusercontent.com/assets/2254151/9249039/78e433f8-41c1-11e5-9c19-f31ae7855fe2.png)

**Comment by christopho** [comment]
I don't have this problem.

**Comment by christopho** [comment]
Already fixed in 1.0.0 (engine bug)
