### ISSUE TITLE
Some issues (rabbit sprite, a map,...)

### ISSUE THREAD

**Issue by Diarandor** [christopho/zelda_roth_se#43]
I have found two things that could be fixed, although nothing important:
-In temple 3 I think, there is an "up" arrow missing in the map (in the right-down corner).
-In temple 4, when the boss transforms you into a rabbit, the "up" direction of the animations look like the down ones. Also, when you push a wall the rabbit becomes transparent (I guess there is no pushing animation in the sprite, but the walking one can still be used).

**Comment by Diarandor** [comment]
-When I obtained the book of Mudora, I didn't see the brandishing sprite (the book did not appear).
-This one I'm not really sure, so I could be wrong (someone should check it). This was in level 3, I think. The door which is opened when the 4 torches are flaming. I think it was opened before all the 4 torches were flaming. I cannot confirm it since I saved the game later.
-In the way after getting the piece of heart to the left of level 5 entrance, there is a map with a tree to the south that "blocks" the hero when you come from the map from the south (the hero gets stuck with the tree after changing the map, altough you can go back to the previous map). It's in the same map where you get the sword.

**Comment by christopho** [comment]
Thanks for these details reports!
For future bugs, can you open a separate issue for each problem (even small ones)? It will be easier for me to track what is remaining to fix.
(No need to do it for the ones already in this bug, it is okay)

**Comment by Diarandor** [comment]
Ok, sorry!

**Comment by christopho** [comment]
I just created separate issues, I am closing this one.
