### ISSUE TITLE
Teleporter not working on the left of the secret dungeon

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#54]
Do go back to the monster village, you can take a shortcut here : 

![image](https://cloud.githubusercontent.com/assets/2254151/9258907/636296d6-41fe-11e5-8b74-35394d6222f4.png)

The teleporter is not active.

**Comment by Renkineko** [comment]
No way to come back by the same path, there is a dead end (first time you use the hookshot on this path).

**Comment by christopho** [comment]
Duplicate of #51

**Comment by Renkineko** [comment]
Yep, saw it after... And it's on the right, I'm so dumb xD
