### ISSUE TITLE
Strange halo when running

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#56]
It's particularly visible on the alternative exit of dungeon 5, when you run right and left where skeletons are : there is a sort of white halo around enemy (probably because it is white), and when you stop the halo cease. I think it can come from the engine (a sort of miscalculating because of the fast speed of the hero ?). It's nearly invisible so maybe not very important (I didn't noticed it on my first play).

**Comment by christopho** [comment]
Cannot reproduce the bug. It could be a graphic card issue or an SDL bug.
