### ISSUE TITLE
Compass is not displaying anything if you don't have the Map

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#63]
In dungeon, if you get the Compass without the Map, when you open the map menu, nothing is shown. I don't know if it's on purpose to reflect the first RotH or if it's a bug.

Same thing for the Map : if you don't have the item and visit the dungeon, the Map is not displayed while you discover it. It's a little strange but again, maybe it's because of the first game ?

**Comment by christopho** [comment]
The original game is like this, I wanted to respect this choice.
