### ISSUE TITLE
Wrong behaviour with gibdo in dungeon 4

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#64]
In this configuration : 

![image](https://cloud.githubusercontent.com/assets/2254151/9263569/9d665046-421e-11e5-9030-6e845861a25a.png)

You cannot kill the gibdo. If the gibdo is always on the same horizontal axis, the flame will never touch it. You have to go more south than him and use the lamp for the flame to connect with the gibdo and kill it. It's a little complicated to apprehend, specifically if you have low magic. If you want a video, I recorded one but didn't yet sent it.

**Comment by christopho** [comment]
Won't fix. Pixels of the fire vs gibdo happen to get this result.
