### ISSUE TITLE
Error in cave "maps/caves/mudora_cave/1f.lua"

### ISSUE THREAD

**Issue by Diarandor** [christopho/zelda_roth_se#67]
I got the following in Error.txt file:

Error: In maps/caves/mudora_cave/1f: [string "maps/caves/mudora_cave/1f.lua"]:7: attempt to index global 'close_door_a_sensor' (a nil value)

**Comment by christopho** [comment]
Fixed in commit https://github.com/christopho/zelda_roth_se/commit/b6825993b76560fa75173f09e500f75cb7d501cf
