### ISSUE TITLE
plantage au game over

### ISSUE THREAD

**Issue by Zakarisz** [christopho/zelda_roth_se#7]
Lorsque le héros meurt, j'ai l'erreur suivante : 
Error: In on_game_over_started: [string "scripts/game_manager.lua"]:227: attempt to call method 'is_rabbit' (a nil value)

**Comment by christopho** [comment]
Merci ! Continue de tester et reporter les erreurs, ça aide beaucoup :)

**Comment by Zakarisz** [comment]
De rien :)
