### ISSUE TITLE
Bug with projectiles from Agahnim

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#70]
As you can see in this video, projectiles can get stuck on the upper corners. Don't know if it's a new bug due to the newest version or if it's old and happens rarily, but I didn't get this bug during my two first playthrough, and here in the same battle got the bug 3 times.

https://youtu.be/LdIZ6b2QNc8

**Comment by Renkineko** [comment]
Projectiles can also get stuck on lower corners.

**Comment by christopho** [comment]
Fixed in the engine: https://github.com/christopho/solarus/commit/756cf0b0ee0c08d4f07164932d9c6e432cba7a29
