### ISSUE TITLE
Music missing in some places

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#74]
According to VL437, Great Fairy Caves and Title Screen are missing musics. Don't know if it's on purpose.

**Comment by christopho** [comment]
Already fixed for fairy caves. I think there is no music in the title screen of the original game, but maybe we should put some.

**Comment by Renkineko** [comment]
IMHO, it can be a way to put the game in wait without music (you save & quit and you let the title screen while you're doing something else like reporting a bug, it avoids a background sound who can interfer with what you want to do). So for me, no music is good. But I can understand it's asked, because a title screen without music is a little sad.

When options will allow to set the music on or off, then a title screen music is ok for me =p

**Comment by christopho** [comment]
Options already allow to change the music and sound volume.
