### ISSUE TITLE
Dungeon 9 : Path blocked when Save & Quit after getting Boss Key

### ISSUE THREAD

**Issue by Renkineko** [christopho/zelda_roth_se#79]
If in dungeon 9 you get the Boss Key (so you have Zelda with you etc), and you save & quit, when you come back after getting Zelda a second time you can't go thru the same path : the chest is already opened and the door is locked.

I think you can fight your way back with the soldiers path, but it's hard for the ultimate rank ^^

**Comment by christopho** [comment]
Yes, the door should remain open.
