### ISSUE TITLE
Beat all enemy types plus chicken = Congrats, you have defeated 47/46 enemies!

### ISSUE THREAD

**Issue by Wuzzy2** [christopho/zelda_roth_se#89]
It is possible to let the game tell you you have 47/46 enemies beaten at the end. How? By killing all enemies in the monsters list AND the chicken in Kakariko Village. You can kill them if you have a powerful sword and patience. xD
The chicken do not appear in the monsters list, but is still counted at the end.

I'd say chicken should not be counted, since it is probably more an easter egg than anything else. Also it might confuse the “enemy counter” guy (not tested!) if you have 45 regular enemies defeated plus the chicken, which sums up to 46. I don't know how the guy will behave in this situation when you talk to him (since I did not test this corner case), but I bet he would congratulate you for defeating “all” enemies, while actually one enemy type is still missing.

Tested with version 1.0.7 on GNU/Linux.

**Comment by christopho** [comment]
Nice catch :)
