### ISSUE TITLE
PNJ de la maison des monstres

### ISSUE THREAD

**Issue by Zakarisz** [christopho/zelda_roth_se#9]
Impossible de parler au PNJ de la maison des monstres à travers le comptoir.
N'ayant pas joué au jeu de Vincent avant, je ne sais pas si c'est le comportement attendu ou s'il manque un PNJ généralisé.

**Comment by christopho** [comment]
C'est un bug, normalement il devrait fonctionner.
EDIT : non j'ai mal lu, les PNJ ne parlent pas à travers les comptoirs dans le jeu.

**Comment by Zakarisz** [comment]
Je parle bien de lui parler à travers le comptoir. Si on fait le tour, ça fonctionne.
J'ai regardé dans l'éditeur et il n'y a pas de PNJ généralisé dans le comptoir.

**Comment by christopho** [comment]
Oui je confirme, c'est voulu comme cela.
