### ISSUE TITLE
Translation of Zelda ROTH-SE into spanish

### ISSUE THREAD

**Issue by Diarandor** [christopho/zelda_roth_se#93]
Hi! 

I opened this issue just to notify that I am working on the spanish translation. Half of the dialogs are already translated at this moment.

EDIT: Good news! I have been working all the night, and all the dialogs are now translated.
It remains to translate the strings.dat file and the images.

**Comment by christopho** [comment]
Nice! :)

**Comment by Diarandor** [comment]
The translation is finished! :D

**Comment by christopho** [comment]
Thanks a lot!
